// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: cmd/proto/server/server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseService_ExecuteCommand_FullMethodName = "/server.DatabaseService/ExecuteCommand"
	DatabaseService_StreamBackup_FullMethodName   = "/server.DatabaseService/StreamBackup"
	DatabaseService_StreamRestore_FullMethodName  = "/server.DatabaseService/StreamRestore"
	DatabaseService_GetLSN_FullMethodName         = "/server.DatabaseService/GetLSN"
)

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 数据库服务器服务
type DatabaseServiceClient interface {
	// 执行数据库命令
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// 数据备份流（server流式发送数据）
	StreamBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error)
	// 数据恢复流（接收流式数据并恢复）
	StreamRestore(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RestoreChunk, RestoreResponse], error)
	// 获取LSN
	GetLSN(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LSNResponse, error)
}

type databaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseServiceClient(cc grpc.ClientConnInterface) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) StreamBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatabaseService_ServiceDesc.Streams[0], DatabaseService_StreamBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupRequest, BackupChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseService_StreamBackupClient = grpc.ServerStreamingClient[BackupChunk]

func (c *databaseServiceClient) StreamRestore(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RestoreChunk, RestoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatabaseService_ServiceDesc.Streams[1], DatabaseService_StreamRestore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RestoreChunk, RestoreResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseService_StreamRestoreClient = grpc.ClientStreamingClient[RestoreChunk, RestoreResponse]

func (c *databaseServiceClient) GetLSN(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LSNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LSNResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetLSN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
// All implementations must embed UnimplementedDatabaseServiceServer
// for forward compatibility.
//
// 数据库服务器服务
type DatabaseServiceServer interface {
	// 执行数据库命令
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	// 数据备份流（server流式发送数据）
	StreamBackup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error
	// 数据恢复流（接收流式数据并恢复）
	StreamRestore(grpc.ClientStreamingServer[RestoreChunk, RestoreResponse]) error
	// 获取LSN
	GetLSN(context.Context, *Empty) (*LSNResponse, error)
	mustEmbedUnimplementedDatabaseServiceServer()
}

// UnimplementedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServiceServer struct{}

func (UnimplementedDatabaseServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedDatabaseServiceServer) StreamBackup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBackup not implemented")
}
func (UnimplementedDatabaseServiceServer) StreamRestore(grpc.ClientStreamingServer[RestoreChunk, RestoreResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRestore not implemented")
}
func (UnimplementedDatabaseServiceServer) GetLSN(context.Context, *Empty) (*LSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSN not implemented")
}
func (UnimplementedDatabaseServiceServer) mustEmbedUnimplementedDatabaseServiceServer() {}
func (UnimplementedDatabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServiceServer will
// result in compilation errors.
type UnsafeDatabaseServiceServer interface {
	mustEmbedUnimplementedDatabaseServiceServer()
}

func RegisterDatabaseServiceServer(s grpc.ServiceRegistrar, srv DatabaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseService_ServiceDesc, srv)
}

func _DatabaseService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_StreamBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServiceServer).StreamBackup(m, &grpc.GenericServerStream[BackupRequest, BackupChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseService_StreamBackupServer = grpc.ServerStreamingServer[BackupChunk]

func _DatabaseService_StreamRestore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatabaseServiceServer).StreamRestore(&grpc.GenericServerStream[RestoreChunk, RestoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseService_StreamRestoreServer = grpc.ClientStreamingServer[RestoreChunk, RestoreResponse]

func _DatabaseService_GetLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetLSN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetLSN(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseService_ServiceDesc is the grpc.ServiceDesc for DatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _DatabaseService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetLSN",
			Handler:    _DatabaseService_GetLSN_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBackup",
			Handler:       _DatabaseService_StreamBackup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRestore",
			Handler:       _DatabaseService_StreamRestore_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "cmd/proto/server/server.proto",
}
