// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: cmd/proto/server/server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{0}
}

// 命令请求
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// 命令响应
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 备份请求
type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{3}
}

func (x *BackupRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

// 备份数据块
type BackupChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{4}
}

func (x *BackupChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BackupChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *BackupChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// 恢复数据块
type RestoreChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreChunk) Reset() {
	*x = RestoreChunk{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreChunk) ProtoMessage() {}

func (x *RestoreChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreChunk.ProtoReflect.Descriptor instead.
func (*RestoreChunk) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestoreChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *RestoreChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// 恢复响应
type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LSN响应
type LSNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           int64                  `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSNResponse) Reset() {
	*x = LSNResponse{}
	mi := &file_cmd_proto_server_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSNResponse) ProtoMessage() {}

func (x *LSNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_server_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSNResponse.ProtoReflect.Descriptor instead.
func (*LSNResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_server_server_proto_rawDescGZIP(), []int{7}
}

func (x *LSNResponse) GetLsn() int64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

var File_cmd_proto_server_server_proto protoreflect.FileDescriptor

const file_cmd_proto_server_server_proto_rawDesc = "" +
	"\n" +
	"\x1dcmd/proto/server/server.proto\x12\x06server\"\a\n" +
	"\x05Empty\"*\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"C\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"5\n" +
	"\rBackupRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\"Y\n" +
	"\vBackupChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"Z\n" +
	"\fRestoreChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"E\n" +
	"\x0fRestoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\vLSNResponse\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x03R\x03lsn2\x82\x02\n" +
	"\x0fDatabaseService\x12A\n" +
	"\x0eExecuteCommand\x12\x16.server.CommandRequest\x1a\x17.server.CommandResponse\x12<\n" +
	"\fStreamBackup\x12\x15.server.BackupRequest\x1a\x13.server.BackupChunk0\x01\x12@\n" +
	"\rStreamRestore\x12\x14.server.RestoreChunk\x1a\x17.server.RestoreResponse(\x01\x12,\n" +
	"\x06GetLSN\x12\r.server.Empty\x1a\x13.server.LSNResponseB\x12Z\x10cmd/proto/serverb\x06proto3"

var (
	file_cmd_proto_server_server_proto_rawDescOnce sync.Once
	file_cmd_proto_server_server_proto_rawDescData []byte
)

func file_cmd_proto_server_server_proto_rawDescGZIP() []byte {
	file_cmd_proto_server_server_proto_rawDescOnce.Do(func() {
		file_cmd_proto_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_server_server_proto_rawDesc), len(file_cmd_proto_server_server_proto_rawDesc)))
	})
	return file_cmd_proto_server_server_proto_rawDescData
}

var file_cmd_proto_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_proto_server_server_proto_goTypes = []any{
	(*Empty)(nil),           // 0: server.Empty
	(*CommandRequest)(nil),  // 1: server.CommandRequest
	(*CommandResponse)(nil), // 2: server.CommandResponse
	(*BackupRequest)(nil),   // 3: server.BackupRequest
	(*BackupChunk)(nil),     // 4: server.BackupChunk
	(*RestoreChunk)(nil),    // 5: server.RestoreChunk
	(*RestoreResponse)(nil), // 6: server.RestoreResponse
	(*LSNResponse)(nil),     // 7: server.LSNResponse
}
var file_cmd_proto_server_server_proto_depIdxs = []int32{
	1, // 0: server.DatabaseService.ExecuteCommand:input_type -> server.CommandRequest
	3, // 1: server.DatabaseService.StreamBackup:input_type -> server.BackupRequest
	5, // 2: server.DatabaseService.StreamRestore:input_type -> server.RestoreChunk
	0, // 3: server.DatabaseService.GetLSN:input_type -> server.Empty
	2, // 4: server.DatabaseService.ExecuteCommand:output_type -> server.CommandResponse
	4, // 5: server.DatabaseService.StreamBackup:output_type -> server.BackupChunk
	6, // 6: server.DatabaseService.StreamRestore:output_type -> server.RestoreResponse
	7, // 7: server.DatabaseService.GetLSN:output_type -> server.LSNResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_server_server_proto_init() }
func file_cmd_proto_server_server_proto_init() {
	if File_cmd_proto_server_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_server_server_proto_rawDesc), len(file_cmd_proto_server_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_server_server_proto_goTypes,
		DependencyIndexes: file_cmd_proto_server_server_proto_depIdxs,
		MessageInfos:      file_cmd_proto_server_server_proto_msgTypes,
	}.Build()
	File_cmd_proto_server_server_proto = out.File
	file_cmd_proto_server_server_proto_goTypes = nil
	file_cmd_proto_server_server_proto_depIdxs = nil
}
